version:  "3"

services:
  mlqa:
    container_name: mlqa
    image: mazenhassani/mlqa
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "python embeddings_generator.py && python app.py && tail -f /dev/null"
    tty: true